modLoader="javafml"
loaderVersion="[37,)" #mandatory
license="All rights reserved"
issueTrackerURL="https://github.com/Epidra/Lucky77/issues"
[[mods]]
modId="lucky77"
version="1.0"
displayName="Lucky77"
displayURL="https://www.curseforge.com/minecraft/mc-mods/lucky77"
logoFile="logo.png"
credits="Thanks for this example mod goes to Java" #optional
authors="Love, Cheese and small house plants" #optional
description='''
Lorem Ipsum
'''
[[dependencies.lucky77]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"