# Basic Info
modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"
issueTrackerURL="https://github.com/Epidra/Lucky77/issues" #optional

# The Mod
[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/lucky77" #optional
logoFile="logo.png" #optional
authors="${mod_authors}" #optional
description='''${mod_description}'''

# The AccessTransformer
[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

# Dependency - NeoForge
[[dependencies."${mod_id}"]] #optional
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="${neo_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"

# Dependency - Minecraft
[[dependencies."${mod_id}"]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
